import os
from crewai import Agent, Task, LLM
from pm_agent import pm_task
from architect_agent import architect_task
from ui_agent import ui_task
from backend_agent import backend_task

llm = LLM(
    model="groq/llama-3.3-70b-versatile",
    temperature=0.1,
    api_key=os.environ["GROQ_API_KEY"]
)

qa_agent = Agent(
    role="QA Lead",
    goal=(
        "Create complete test strategy for FlyEasy. "
        "Cover every screen, API, edge case, and security vulnerability. "
        "Produce test cases, Postman collection, Playwright script, and bug template."
    ),
    backstory=(
        "10 years testing OTA and travel booking platforms. "
        "Expert in GDS edge cases: fare expiry after 15 mins, "
        "seat sold between search and booking, price change during session. "
        "Skilled in functional, regression, performance, and security testing. "
        "Uses Playwright for E2E, Jest for unit tests, Postman for API testing. "
        "Knows OWASP Top 10 and PCI DSS testing requirements."
    ),
    llm=llm,
    verbose=True,
    allow_delegation=False
)

qa_task = Task(
    description=(
        "Create complete QA package for FlyEasy flight portal.\n\n"

        "DELIVERABLE 1 - 50 FUNCTIONAL TEST CASES:\n"
        "Each test case must have ID, description, steps, expected result, severity.\n\n"

        "SEARCH FLOW 10 cases:\n"
        "TC01 Valid one-way search DEL to DXB returns results within 5 seconds.\n"
        "TC02 Valid round-trip search with return date shows both legs.\n"
        "TC03 Multi-city search with 3 legs works correctly.\n"
        "TC04 Search with no available flights shows empty state message.\n"
        "TC05 Search with past departure date shows validation error.\n"
        "TC06 Search without selecting origin airport shows error.\n"
        "TC07 Search without selecting destination airport shows error.\n"
        "TC08 Swap origin and destination button reverses both values correctly.\n"
        "TC09 Passenger selector enforces maximum 9 total passengers.\n"
        "TC10 Adding infant without adult passenger shows validation error.\n\n"

        "RESULTS PAGE 8 cases:\n"
        "TC11 Flight results load and display within 5 seconds.\n"
        "TC12 Sort by cheapest reorders all results by price ascending.\n"
        "TC13 Sort by fastest reorders all results by duration ascending.\n"
        "TC14 Filter by zero stops shows only non-stop flights.\n"
        "TC15 Filter by specific airline shows only that airline flights.\n"
        "TC16 Price range filter removes flights outside selected range.\n"
        "TC17 Loading skeleton cards display during API call.\n"
        "TC18 Clicking a flight card navigates to correct flight detail page.\n\n"

        "BOOKING FLOW 12 cases:\n"
        "TC19 Passenger form blocks submission when required fields are empty.\n"
        "TC20 Invalid passport number format is rejected with error message.\n"
        "TC21 Invalid email format is rejected with error message.\n"
        "TC22 Phone number without plus 91 prefix shows format error.\n"
        "TC23 Seat selection persists correctly for each passenger.\n"
        "TC24 Skip seat selection link proceeds directly to payment page.\n"
        "TC25 15 minute countdown timer is visible and running on payment page.\n"
        "TC26 Timer reaching zero shows fare expired message with option to search again.\n"
        "TC27 Successful test card payment completes booking and shows PNR.\n"
        "TC28 Successful UPI test payment completes booking and shows PNR.\n"
        "TC29 Failed payment shows error message with retry payment option.\n"
        "TC30 Confirmation page displays correct PNR in large format.\n\n"

        "TICKET FLOW 5 cases:\n"
        "TC31 E-ticket page loads with all correct data for given PNR.\n"
        "TC32 All passenger names display correctly on e-ticket.\n"
        "TC33 Print button triggers browser print dialog correctly.\n"
        "TC34 Booking confirmation email arrives within 2 minutes of payment.\n"
        "TC35 WhatsApp share button generates link containing PNR and route.\n\n"

        "EDGE CASES 15 cases:\n"
        "TC36 Fare expired between search and booking shows clear expired message.\n"
        "TC37 Seat sold between search and booking offers alternative options.\n"
        "TC38 Price increased between search and payment shows price change alert.\n"
        "TC39 Amadeus API timeout after 30 seconds shows friendly retry message.\n"
        "TC40 Payment success but PNR creation failed shows support contact message.\n"
        "TC41 Attempting duplicate booking for same flight and passenger is blocked.\n"
        "TC42 Browser back button during payment page does not lose entered data.\n"
        "TC43 Page refresh during passenger form restores data from Zustand store.\n"
        "TC44 Slow 3G network simulation shows loading states on all pages.\n"
        "TC45 Network disconnect during payment shows connection error with recovery.\n"
        "TC46 Accessing ticket page with invalid PNR returns 404 not found page.\n"
        "TC47 Accessing payment page directly without completing passengers redirects back.\n"
        "TC48 Accessing confirm page directly without completing payment redirects back.\n"
        "TC49 Multi-city search with identical origin and destination is blocked.\n"
        "TC50 Booking with infant count exceeding adult count is blocked.\n\n"

        "DELIVERABLE 2 - POSTMAN COLLECTION JSON:\n"
        "Produce complete Postman collection JSON with all requests and tests.\n"
        "Collection name: FlyEasy API Tests.\n"
        "Folder 1 Flights: POST /api/flights/search with valid payload expect 200 results array, "
        "POST with missing origin expect 400 error message, "
        "POST with past date expect 400 validation error.\n"
        "GET /api/flights/offerId with valid id expect 200 offer details, "
        "GET with expired id expect 410 Gone, "
        "GET with invalid format expect 400.\n"
        "Folder 2 Bookings: POST /api/bookings/create with valid payload expect 200 PNR, "
        "POST with missing passengers expect 400, "
        "POST with no auth token expect 401, "
        "POST with expired token expect 401.\n"
        "Folder 3 Payments: POST /api/payments/initiate with valid payload expect 200 orderId, "
        "POST with invalid bookingId expect 404, "
        "POST /api/payments/verify with valid signature expect 200 success, "
        "POST with invalid signature expect 400 mismatch, "
        "POST with already verified payment expect 409 conflict.\n"
        "Folder 4 Tickets: GET /api/tickets/pnr with valid PNR expect 200 ticket data, "
        "GET with invalid PNR expect 404, "
        "GET with another users PNR expect 403 forbidden.\n"
        "Folder 5 Notifications: POST /api/notifications/ticket valid payload expect 200 messageId, "
        "POST with invalid email expect 400.\n\n"

        "DELIVERABLE 3 - SECURITY CHECKLIST:\n"
        "Produce pass or fail checklist with test steps for each item.\n"
        "SQL injection attempt in search origin field must return 400 not execute.\n"
        "SQL injection in passenger name fields must be sanitized.\n"
        "XSS script tag in first name field must be escaped not rendered.\n"
        "XSS script tag in last name field must be escaped not rendered.\n"
        "IDOR test: user A requests user B PNR via URL must return 403.\n"
        "IDOR test: user A requests user B payment record must return 403.\n"
        "Razorpay signature tampering must return 400 invalid signature.\n"
        "Expired JWT token on booking route must return 401.\n"
        "Missing JWT token on payment route must return 401.\n"
        "Rate limit 100 searches per minute per IP must return 429 when exceeded.\n"
        "Passport number must not appear in any API response logs.\n"
        "Card data must never appear in database or logs.\n"
        "All pages must redirect HTTP to HTTPS.\n"
        "CORS must block requests from non flyeasy.com origins.\n"
        "Content-Security-Policy header must be present on all pages.\n\n"

        "DELIVERABLE 4 - PLAYWRIGHT E2E TEST SCRIPT:\n"
        "Produce complete file tests/e2e/booking-flow.spec.ts.\n"
        "Import test and expect from playwright/test.\n"
        "Test name: completes full flight booking happy path.\n"
        "Step 1: navigate to localhost 3000.\n"
        "Step 2: click one way trip type button.\n"
        "Step 3: fill origin input with DEL.\n"
        "Step 4: click Indira Gandhi International from dropdown.\n"
        "Step 5: fill destination input with DXB.\n"
        "Step 6: click Dubai International from dropdown.\n"
        "Step 7: fill departure date with date 30 days from today.\n"
        "Step 8: verify passenger count shows 1 adult.\n"
        "Step 9: click Search Flights button.\n"
        "Step 10: wait for URL to contain flights/search.\n"
        "Step 11: expect at least 1 flight result card to be visible.\n"
        "Step 12: click first flight result card.\n"
        "Step 13: wait for URL to contain flights.\n"
        "Step 14: expect flight details page heading to be visible.\n"
        "Step 15: click Select This Flight button.\n"
        "Step 16: wait for URL to contain booking/passengers.\n"
        "Step 17: fill title select with Mr.\n"
        "Step 18: fill first name with Test.\n"
        "Step 19: fill last name with Passenger.\n"
        "Step 20: fill date of birth with 1990-01-01.\n"
        "Step 21: fill passport number with A1234567.\n"
        "Step 22: fill email with test@flyeasy.com.\n"
        "Step 23: fill phone with 9999999999.\n"
        "Step 24: click Continue to Seat Selection button.\n"
        "Step 25: wait for URL to contain booking/seats.\n"
        "Step 26: click Skip Seat Selection link.\n"
        "Step 27: wait for URL to contain booking/payment.\n"
        "Step 28: expect countdown timer to be visible.\n"
        "Step 29: expect order summary to show amount greater than 0.\n"
        "Step 30: complete Razorpay test payment using test card 4111111111111111.\n"
        "Step 31: wait for URL to contain booking/confirm.\n"
        "Step 32: expect PNR element to be visible and contain 6 characters.\n"
        "Step 33: click Download E-Ticket button.\n"
        "Step 34: wait for URL to contain booking/ticket.\n"
        "Step 35: expect passenger name Test Passenger to be visible on ticket.\n\n"

        "DELIVERABLE 5 - BUG REPORT TEMPLATE:\n"
        "Produce markdown template file docs/bug-report-template.md.\n"
        "Fields: Bug ID, Title, Severity Critical High Medium Low, "
        "Module Search Results Booking Payment Ticket, "
        "Environment Dev Staging Prod, "
        "Steps to Reproduce as numbered list, "
        "Expected Result, Actual Result, "
        "Screenshot or Video URL, "
        "Browser and OS, "
        "Reported By, Reported Date, "
        "Assigned To, "
        "Status Open InProgress Fixed Closed, "
        "Fix Verified By, Fix Verified Date.\n\n"

        "DELIVERABLE 6 - PERFORMANCE BENCHMARKS:\n"
        "Produce docs/performance-benchmarks.md.\n"
        "Home page initial load under 2 seconds on 4G network.\n"
        "Flight search API response under 5 seconds end to end.\n"
        "Results page render after API response under 1 second.\n"
        "Flight detail page load under 1.5 seconds.\n"
        "Payment page with Razorpay widget load under 3 seconds.\n"
        "E-ticket page load under 1 second.\n"
        "Minimum 500 concurrent users supported without degradation.\n"
        "API error rate must stay below 0.1 percent under normal load.\n"
        "Razorpay payment processing under 10 seconds end to end.\n"
        "Brevo email delivery within 2 minutes of payment confirmation.\n"
    ),
    agent=qa_agent,
    expected_output=(
        "Complete QA package with all 6 deliverables: "
        "50 test cases with steps and expected results, "
        "Postman collection JSON, "
        "security checklist with 15 items, "
        "Playwright E2E script booking-flow.spec.ts, "
        "bug report template markdown, "
        "performance benchmarks markdown."
    ),
    context=[pm_task, architect_task, ui_task, backend_task]
)
